### ISSUE TITLE
Circumventing persistent queue between commands

### ISSUE THREAD

**Issue by micnorian14** [hydrusvideodeduplicator/hydrus-video-deduplicator#17]
I'm trying to run the program with queries that limit the results so as not to queue my entire library. Command --query="system:duration < 2s resulted in a few hundred candidates which processed just fine. But --query="system:duration < 3s resulted in thousands of candidates giving me an exorbitant processing ETA. I halt the command then try something more specific only to have the same days long ETA. I know this is a feature but I'm trying to circumvent it. Here's the breakdown: 

>Run --query="system:duration < 3s" It identifies ~3000 candidates
>Halt because the ETA is 120+ hours
>Attempt to use a different more narrower search like --query="creator:micnorian" resulting in only 300 candidates
>The program appends these 300 results to the 3000+ it queued with the prior command
>ETA 121+ hours to process 3,300 candidates
>Trying a few other commands just makes it worse
>Must wait for queue to finish to continue testing

**Comment by appleappleapplenanner** [comment]
The program is split up into two parts currently: calculating perceptual hashes and searching for duplicates.

I'm assuming by processing you mean it's searching for duplicates. Query does not currently affect searching for duplicates. That's actually what I'm working on right now.

What you can do right now is delete or move your database if you want to do some testing. The database is `~/.local/share/hydrusvideodeduplicator/videohashes.sqlite`

**Comment by appleappleapplenanner** [comment]
Okay, duplicate search should be restricted to query parameters in the newest version, 0.1.17. Try it out.

**Comment by prof-m** [comment]
@appleappleapplenanner , I'd actually just been wondering about this as I'd been testing it out with my own library. So does this mean that if I have tags `tagA` and `tagB`, and a bunch of files that are tagged with either or both tags, and I run the program twice - once with `--query="tagA"` and once with `--query="tagB"`, the first run will search for duplicates only among files with `tagA`, and the second run will only search for duplicates among `tagB`? But in both cases, the app won't look for duplicates in the phashes generated by prior searches?

**Comment by appleappleapplenanner** [comment]
> For batching purposes, I know I'd personally like to be able to reference the results from previous batches when searching for duplicates in the new batches, but I can see why folks might sometimes only want to search for duplicates within a specific tag - especially as I'm noticing that the 'finding duplicates' process seems to naturally take exponentially longer the more perceptual hashes I already have. Having an option to decide how much of the built up perceptual hashes library you want to check for duplicates could be useful for both cases here.

You could do this if you could just run the union of the queries. But, I cannot figure out how to get OR predicates working with the hydrus-api Python library I'm using.

Finding duplicates does not take exponentially longer. It will take (n^2 - n) / 2 time for n videos. But, if you don't use queries for the duplicates _**search**_ it will go much faster on subsequent runs if you let it finish because it will only check for duplicates on new entries in the database. This is because the database is ordered.

But now that you mention it, I can actually speed up the searching for duplicates in query searches by doing the same thing I do with non-query searches.

**Comment by ianwal** [comment]
> Okay, duplicate search should be restricted to query parameters in the newest version, 0.1.17. Try it out.

Actually, I don't like this. All files should just be compared for simplicity, the only limiting factor is compare speed. I'm going to revert this in the future.

**Comment by prof-m** [comment]
@ianwal When you say "all files", do you mean "all available phashed files, regardless of query arguments", or "all files like removing the `--query` parameter entirely"? Cause I definitely agree with the first approach, but the second approach feels like overkill in how it removes any ability to do chunks in stages.

**Comment by ianwal** [comment]
> Cause I definitely agree with the first approach, but the second approach feels like overkill in how it removes any ability to do chunks in stages.

Query is good. Not using the cache for queries by default is bad and confusing. Finding duplicates doesn't really take that long, so not using the cache for queries was a bad idea. I'll probably retain the option to compare only against a query search with no cache, but that might change in the future if search speed is improved.

**Comment by ianwal** [comment]
Changed in 6b2511f and released in v0.4.0. `--query` now compares against all items in the database once again.
