### ISSUE TITLE
Database disk image is malformed

### ISSUE THREAD

**Issue by Tisaghu** [hydrusvideodeduplicator/hydrus-video-deduplicator#41]
I am getting the error "sqlite3.DatabaseError: database disk image is malformed" when I try to run the program.
It occurs when I get about 23% of the way through clearing trashed videos. Here is a copy of my command prompt output:

 Hydrus Video Deduplicator 0.3.1
Connecting to http://127.0.0.1:45869
 Database found with 20966 videos already hashed.
Clearing trashed videos:  23%|███████████▏                                    | 4864/20966 [00:49<00:57, 280.48video/s]Exception in thread Thread-2:
Traceback (most recent call last):
  File "C:\Users\samas\AppData\Local\Programs\Python\Python310\lib\threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "C:\Users\samas\AppData\Local\Programs\Python\Python310\lib\site-packages\sqlitedict.py", line 517, in run
    conn.commit()
sqlite3.DatabaseError: database disk image is malformed
Clearing trashed videos:  23%|███████████▏                                    | 4864/20966 [01:00<00:57, 280.48video/s]

It just hangs here forever.

**Comment by ianwal** [comment]
First, before doing anything else, backup your DB. It should be in `%USERPROFILE%\AppData\Local\hydrusvideodeduplicator` or `%USERPROFILE%\AppData\Roaming\hydrusvideodeduplicator`. Just copy it somewhere safe.

Then try upgrading the program with `pip install hydrusvideodeduplicator --upgrade`. I don't think it will fix anything, but you're on an outdated version. Let me know if that fixes it.

**Comment by Tisaghu** [comment]
Upgrading didn't fix it, but thank you for the help with that. The integrity check and vacuum seem to have done the trick. Thank you very much for the help!
