### ISSUE TITLE
Assertion Error on 0.5.0

### ISSUE THREAD

**Issue by Stealthbird97** [hydrusvideodeduplicator/hydrus-video-deduplicator#54]
Updated to 0.5.0

Getting a large number of errors and finally Assertion error

[error.txt](https://github.com/user-attachments/files/15827020/error.txt)

**Comment by ianwal** [comment]
That looks like an issue with the FFmpeg bindings Python library, PyAV. 

The only changed from v0.4 to v0.5 was adding documentation.

Do you know what version you upgraded from? What OS are you on? Possibly downgrading av to what version you had before would solve the issue.

**Comment by Stealthbird97** [comment]
I suspect I had 0.4.3 but I don't think I've run the software for a while and didn't check before updating.
Currently running the latest Hydrus v578 on windows 11.

I've opened hydrus and searched by hash for the very first file listed in the video_hashes list seen in the error log, and it seems that the error is with the file rather than the program.
Just looking I've found like 10 files with similar issues which will likely crash the program mid-way. Not really feasible to manually fix delete these as the only way to tell is the lack of a thumbnail in hydrus.

Probably need some more error handling.

**Comment by ianwal** [comment]
> I suspect I had 0.4.3 but I don't think I've run the software for a while and didn't check before updating. Currently running the latest Hydrus v578 on windows 11.
> 
> Not really feasible to manually fix delete these as the only way to tell is the lack of a thumbnail in hydrus.

Feel free to install what's on the develop branch which has the new failed pages feature that will add those bad videos into a page you create in Hydrus after they fail to hash.

**Comment by Stealthbird97** [comment]
What is the option I need to give to tell it which page to add the failures to?

**Comment by ianwal** [comment]
Confirmed with you that video files were corrupted and crashing mpv when opened.

More extensive error handling would be a nice improvement, but removing corrupted video files is a good enough solution.
